import { CommandMap } from "@/types";

export const commands: CommandMap = {
  help: [
    "Available commands:",
    "",
    "  about       - Who am I",
    "  projects    - Things I've built",
    "  skills      - Technologies I work with",
    "  resume      - Get my resume",
    "  contact     - How to reach me",
    "  clear       - Clear terminal",
    "  help        - Show this message",
  ],
  about: [
    "Hey! I'm Saba Karazanashvili — a Computer Science student",
    "focused on backend and full-stack engineering.",
    "",
    "I build systems where the logic actually matters — APIs,",
    "data flow, and scalable backend architecture.",
    "",
    "I've worked on full-stack applications using Java Spring Boot",
    "and modern frontend frameworks, along with projects involving",
    "blockchain data and real-world problem solving.",
    "",
    "Currently focused on backend systems, cloud, and preparing",
    "for software engineering internships.",
    "",
    'Type "projects" to see what I\'ve built.',
  ],
  projects: [
    "1. TutorRev — tutorrev.live",
    "   A full-stack platform where students can review and",
    "   rate online tutorials.",
    "   Tech: Java, Spring Boot, MongoDB, JWT, OAuth, React",
    "   Link: https://tutorrev.onrender.com",
    "",
    "2. Crypto Tax Tool",
    "   A multi-wallet Solana transaction analyzer that",
    "   calculates cost basis and profit/loss.",
    "   Tech: Python, Helius API, blockchain data parsing",
    "   Link: https://github.com/skarazan",
    "",
    "3. Terminal Portfolio",
    "   Interactive terminal-style portfolio where users",
    "   explore content through command inputs.",
    "   Tech: Next.js, React, TypeScript, Tailwind",
    "   Link: https://github.com/skarazan",
  ],
  skills: [
    "Languages:    Java, Python, TypeScript",
    "Frontend:     React, Next.js, Tailwind CSS",
    "Backend:      Spring Boot, REST APIs, JWT Auth, OAuth",
    "Databases:    MongoDB, SQL",
    "Tools:        Git, Docker, AWS (basic)",
  ],
  resume: [
    "Opening resume...",
    "",
    "→ /resume.pdf",
    "",
    "Currently seeking Software Engineering internships",
    "for Summer 2027.",
    "",
    'Type "contact" to get in touch.',
  ],
  contact: [
    "Email:    skarazan@nyit.edu",
    "GitHub:   https://github.com/skarazan",
    "LinkedIn: https://www.linkedin.com/in/saba-kara/",
    "",
    "Feel free to reach out — I'm always happy to connect.",
  ],
};

export const BOOT_MESSAGES: string[] = [
  "Initializing portfolio...",
  "Loading projects...",
  "System ready.",
  "",
  "Type 'help' to begin.",
];
